-- +goose Up
-- Stage 40: per-image Software Bill of Materials, generated by syft.
ALTER TABLE images
    ADD COLUMN sbom_status       TEXT,        -- 'pending' | 'ok' | 'error'
    ADD COLUMN sbom_generated_at TIMESTAMPTZ,
    ADD COLUMN sbom_format       TEXT,        -- 'spdx-json' | 'cyclonedx-json'
    ADD COLUMN sbom_data         JSONB;       -- the parsed document

-- +goose Down
ALTER TABLE images DROP COLUMN sbom_data;
ALTER TABLE images DROP COLUMN sbom_format;
ALTER TABLE images DROP COLUMN sbom_generated_at;
ALTER TABLE images DROP COLUMN sbom_status;
